# Generated by Django 4.1.7 on 2023-03-08 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FleetVehicleModelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('category_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FleetVehicleOdometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=100)),
                ('date_join', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('model_year', models.IntegerField(default=0)),
                ('fuel_type', models.CharField(max_length=100)),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_type_brand', to='app.vehicletype')),
            ],
        ),
        migrations.CreateModel(
            name='FleetVehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('seats', models.IntegerField(blank=True, null=True)),
                ('doors', models.IntegerField(blank=True, null=True)),
                ('power', models.IntegerField(blank=True, null=True)),
                ('horsepower', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('co2_standard', models.CharField(blank=True, max_length=100, null=True)),
                ('default_fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(blank=True, null=True)),
                ('trailer_hook', models.BooleanField(blank=True, null=True)),
                ('electric_assistance', models.BooleanField(blank=True, null=True)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('write_date', models.DateTimeField(blank=True, null=True)),
                ('default_co2', models.FloatField(blank=True, null=True)),
                ('horsepower_tax', models.FloatField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.vehiclebrand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.fleetvehiclemodelcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_short_name', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=100)),
                ('vin_sn', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=100)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='app.vehicleemployee')),
                ('odomoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odomoter', to='app.fleetvehicleodometer')),
                ('vehicle_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_brand', to='app.fleetvehiclemodel')),
                ('vehicle_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_category', to='app.fleetvehiclemodelcategory')),
            ],
        ),
    ]
